-- repl.Window(0)
-- repl.WidgetRenderer()
-- f = wid.CreateFont("res/fonts/font.ttf", 32)
-- t = wid.CreateTextLabel(vec3(100, 100, 1), vec3(0), f, "Hello", vec4(1, 0, 0, 1))
-- b = wid.CreateButton(vec3(100, 100, 1), vec3(0), function() print("hello") end, true)

repl.Window(0)
w = repl.w
r_shape = Jkr.CreateShapeRenderer3D(Engine.i, w)
world = Jkr.World3D(r_shape)
camera = Jkr.Camera3D()
camera:SetAttributes(vec3(0, 0, 0), vec3(0, -10, 10))
camera:SetPerspective(0.3, 16 / 9, 0.1, 10000)
world:AddCamera(camera)
print("FUCK YOU")
Engine.AddAndConfigureGLTFToWorld(w, world, r_shape, "res/models/CesiumManBlend/CesiumMan.gltf", "CONSTANT_COLOR")
print("FUCK YOU2")
